### ISSUE TITLE
Incorrect content type for files in listing response 

### ISSUE THREAD

**Issue by IlyaBondar** [epam/ai-dial-core#115]
### Description
Broken image displaying because UI receives incorrect content types in file listing response:
![image](https://github.com/epam/ai-dial-core/assets/20163971/c437159b-61a4-4a93-915f-6a9c2a5b2287)

#### Steps to reproduce
1) use GPT Vision model
2) upload image (jpg or png) initially i.e. for first message (image can be expanded and displayed)
![image](https://github.com/epam/ai-dial-core/assets/20163971/92645c3d-90d3-465c-a9a4-e4c318f2af31)
3) then reuse this already used image for next message 
#### Actual result:
image was received with listing with incorrect content type -> image can be expanded/displayed
![image](https://github.com/epam/ai-dial-core/assets/20163971/46240716-dc78-48c7-ad80-e43e98594990)
#### Expected result 
receive correct content type

**Comment by Maxim-Gadalov** [comment]
AWS S3 do not provide a content type without additional head request. We decided to resolve content type based on file extension.
