### ISSUE TITLE
"Error happened during getting file user bucket" (500 error) appears when not authorized user opens overlay

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-core#122]
Open landing page connected to staging server -> As user is not authorized "Error happened during getting file user bucket" appears. 500 error is in console -> **bug**

![image](https://github.com/epam/ai-dial-core/assets/111180458/77007b42-f655-4109-8326-a550b474b77e)

**Expected result**: there should be 401 status code

Note for testers:
There are also reported issue on chat board: 
https://github.com/epam/ai-dial-chat/issues/425
https://github.com/epam/ai-dial-chat/issues/352

**Comment by astsiapanay** [comment]
It's not reproduced any longer. 
Closed as invalid.
