### ISSUE TITLE
IAM role authentication for access to aws-s3 blob storage

### ISSUE THREAD

**Issue by showroute** [epam/ai-dial-core#132]
Hi,

It would be nice to implement IAM role authentication for access to `aws-s3` blob storage. For now it supports only IAM user credentials. This change would help to avoid secret rotation that must be done periodically.

https://github.com/epam/ai-dial-core/blob/0.5.0/src/main/java/com/epam/aidial/core/config/Storage.java

**Comment by astsiapanay** [comment]
resolved by #235
