### ISSUE TITLE
ai_core healthcheck unavailable 

### ISSUE THREAD

**Issue by Banzydev** [epam/ai-dial-core#14]
Hello!

I'm trying to deploy an application to AWS ECS. 
But since the aicore container does not have a healscheck, it is not possible to run it using AWS ALB. AWS ALB cannot perform a healscheck on an application and recreates the task in AWS ECS every time

**Comment by adubovik** [comment]
@Banzydev Hi, please try out the latest image `ghcr.io/epam/ai-dial-core:0.2.1`

It serves health check at `:8080/health`
