### ISSUE TITLE
Add validation for config to match controller patterns 

### ISSUE THREAD

**Issue by nepalevov** [epam/ai-dial-core#197]
In `src/main/java/com/epam/aidial/core/controller/ControllerSelector.java` there are naming regexes for models, deployments, etc. e.g.:

``` java
private static final Pattern PATTERN_DEPLOYMENT = Pattern.compile("/+openai/deployments/([-.@a-zA-Z0-9]+)");
private static final Pattern PATTERN_MODEL = Pattern.compile("/+openai/models/([-.@a-zA-Z0-9]+)");
private static final Pattern PATTERN_ADDON = Pattern.compile("/+openai/addons/([-.@a-zA-Z0-9]+)");
private static final Pattern PATTERN_ASSISTANT = Pattern.compile("/+openai/assistants/([-.@a-zA-Z0-9]+)");
private static final Pattern PATTERN_APPLICATION = Pattern.compile("/+openai/applications/([-.@a-zA-Z0-9]+)");
```

This implements special constraints on how models, deployments, assistants, and applications should be named. However, there is no

1. information about special chars, cases, and length constraints in documentation
1. config validation exceptions for invalid names (application should fail to start if an invalid name is used)

**Comment by artsiomkorzun** [comment]
Fixed in #200. Now deployments with any characters are supported. Given that, one needs to encode reserved characters in HTTP path.
