### ISSUE TITLE
Design and implement generic way to set parameters for applications/adapters

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-core#220]
MVP cases:
| Usecase  |  Deployment  | User  |  Comments  |
|---|---|---|---|
| Model selection  |  DIAL RAG |  UI Users / Derived applications which uses RAG API  | |
| Error reporting type  |  DIAL RAG  |  Web RAG Programmatically  |   |
| Dataset selection | danswer app |  UI User | | 
| Dataset list | danswer app| UI User| |
| Retry count | SUB-PROJECT-1 | UI User, potentially API user | |
| Get data | StatGPT | IMF UI User | Option is only available when all query parameters are filled | 
| Select API Search indices or copilot  | MSFT RAG demo | Sales person |  | 

Seems like we have at least two simple cases:
1. Application Settings
2. Contextual  commands

**Comment by astsiapanay** [comment]
The task is longer valid.
