### ISSUE TITLE
Investigate and implement additional cloud authorization options for blob storage and models

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-core#222]
As a first step we need to create list of options worth supporting.

List of tasks:

- [X] Issue #235 
- [X] Issue #239 
- [X] Issue #251
- [X] Issue https://github.com/epam/ai-dial-adapter-openai/issues/74

**Comment by alexey-ban** [comment]
Auth method in cloud managed kubernetes
---
EKS - https://docs.aws.amazon.com/eks/latest/userguide/service-accounts.html
* IAM roles for service accounts
* EKS Pod Identities

---
AKS - https://azure.github.io/azure-workload-identity/docs/
 
* Microsoft Entra Workload ID with Azure Kubernetes Service
---
GKE - https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity

* Workload identity federation for GKE
