### ISSUE TITLE
Chat conversations dissapear if core component is restarted

### ISSUE THREAD

**Issue by photonn** [epam/ai-dial-core#300]
With default settings, conversations dissapear in chat UI if more than 256 seconds since creation passed for the conversation + core pod is deleted. To reproduce:

ssh in core and get this:
 
/app/data/dial $ tree .
.
└── Users
    └── DAJTO9-gvz7KbCkt1fsFGj2DCbOM6F7NIrm8AMy5DyU
        └── conversations
            ├── gpt-35-turbo__summarize little women plot
            ├── gpt-35-turbo__tell a nasty joke
            ├── gpt-35-turbo__tell me all that you know about french revolution
            └── gpt-35-turbo__write a haiku
 
close chat
restarted core
 
ssh to core and get this:
 
/app/data/dial $ tree .
.
└── Users
    └── DAJTO9-gvz7KbCkt1fsFGj2DCbOM6F7NIrm8AMy5DyU
        └── conversations
            ├── gpt-35-turbo__summarize little women plot
            ├── gpt-35-turbo__tell a nasty joke
            └── gpt-35-turbo__write a haiku

in chat ui i see this:
 
 
 
close chat again
restarted core pod 
ssh into it and got this:
 
/app/data/dial $ tree .
.
 
and in chat ui there is no conversations:

 
in core logs i see this warn:
 
2024-04-05 09:05:57.419 WARN [vert.x-eventloop-thread-1] Responding with error. Trace: a89d0377277711297b2b15e903df9ebf. Span: 0a6b1a9623c7ace9. Status: NOT_FOUND. Body: Not found: conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke
 
in chat, isee this log:
 
[09:05:57.426] ERROR (18): Requesting entity failed - '[http://dial-core/v1/conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke'Not](http://dial-core/v1/conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke%27Not) Found [trace_id=a89d0377277711297b2b15e903df9ebf, span_id=24477c3bfb8380c8]
    trace_id: "a89d0377277711297b2b15e903df9ebf"
    span_id: "24477c3bfb8380c8"
    trace_flags: "01"
    err: {
      "type": "DialAIError",
      "message": "Requesting entity failed - '[http://dial-core/v1/conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke'Not](http://dial-core/v1/conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke%27Not) Found",
      "stack":
          DialAIError: Requesting entity failed - '[http://dial-core/v1/conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke'Not](http://dial-core/v1/conversations/PZh2M4YFYTumimKw14TH26xgBTE9soqtSfH698rMH6GNq1ccg8pxTxoaUHqWAVKREAk8WVN7EykVAYDpCrEa5Kd/gpt-35-turbo__tell%20a%20nasty%20joke%27Not) Found
              at handleGetRequest (/app/.next/server/pages/api/[entitytype]/[...slug].js:1:3199)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async handler (/app/.next/server/pages/api/[entitytype]/[...slug].js:1:2082)
      "name": "DialAIError",
      "param": "",
      "code": "404"
    }
    
    Also, I tested redis config:

127.0.0.1:6379> KEYS *
1) "invitation:Users/DAJTO9-gvz7KbCkt1fsFGj2DCbOM6F7NIrm8AMy5DyU/invitations/invitations"

127.0.0.1:6379> TTL invitation:Users/DAJTO9-gvz7KbCkt1fsFGj2DCbOM6F7NIrm8AMy5DyU/invitations/invitations
(integer) 256

127.0.0.1:6379>

look like by default, redis keys are marked to delete every 256 seconds. if after that time the core pod is deleted and started again, conversations are lost.

**Comment by photonn** [comment]
we are using core component version 0.8.1 and redis config in our values.yaml file is this:

redis:
   enabled: true
   password: "xxxxxxx"

**Comment by photonn** [comment]
After conversations with Aliaksandr, permanent storage configuration is mandatory since 0.5 as conversations are migrated to it. Ill try to configure a container and check if this goes away. 

   Anyway, if storage is a mandatory piece of the architecture, core should not be allowed to run if it is not configured.

**Comment by astsiapanay** [comment]
closed as invalid.
