### ISSUE TITLE
Attachment should be marked as unshared when related chat was unshared

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-core#310]
**How to reproduce**
User 1 create chat with file pdf (DIAL RAG or echo)
User1 share chat with file
User2 open shared link
User1 open shared chat
User1 revoke access to this file chat
User1 open Manage Attachment form and find file attached to the chat
**Actual result**: Chat marked as unshared, arrow is removed from chat icon ->ok
File is still marked as shared : arrow is displayed on the file icon-> bug
![image](https://github.com/epam/ai-dial-chat/assets/77381071/dddc501c-fac4-42bc-9d79-bbf90be12e46)

Note: file also is not unshared when user1 change model to shared chat

**Expected result**
File should be shown as unshared ( without arrow on file icon)

**Comment by VolhaBazhkova** [comment]
Agreed with @sdryapko on daily-status-call that it's expected behavior.
