### ISSUE TITLE
Pathtrough Upvote/Downvote to Application/Adapters

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-core#32]
* User's upvote / downvote actions need to be delivered all the way to custom applications/assistants
* Message need to be identified by response ID, no history will be provided
* The feature is supposed to be optional: switchable via core config. We need avoid issues if destination does not support upvote/downvote
* SDK and samples (echo) need to be modified to support the feature
* Corresponding changes need to be done in APIs and front-end

**Comment by astsiapanay** [comment]
depends on https://github.com/epam/ai-dial-sdk/issues/39
