### ISSUE TITLE
feature request: allow providing "Max tokens" parameter in web UI

### ISSUE THREAD

**Issue by justrp** [epam/ai-dial-core#331]
DIAL core (API) allows you to specify `max_prompt_tokens` parameters, but DIAL Chat (web UI) does not.
As a user of Web UI (DIAL Chat), I want to be able to specify that parameter.

This issue will collect user feedback to see if team needs to prioritize this feature. Currently we have a single request.

**Comment by astsiapanay** [comment]
@justrp isn't the issue of https://github.com/epam/ai-dial-chat. I guess the Core has nothing to do here.

**Comment by astsiapanay** [comment]
The issue doesn't relate to the Core but Chat UI.
closed as invalid.
