### ISSUE TITLE
Sharing: support folders referenced via metadata URL

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-core#338]
How to reproduce the issue in DIAL Chat: 
1. create a conversation which contains a folder attachment
2. share this conversation

This leads to 400 error coming from Core.
Folder attachments are represented as links to corresponding metadata.
However, Core doesn't support metadata URLs, thus the error.

![MicrosoftTeams-image](https://github.com/epam/ai-dial-core/assets/4329926/06cd8534-ef04-4363-959f-2d49d1bbb418)

We need to support the metadata links to folders in Core - simply strip their `metadata/` prefix.

**Comment by IlyaBondar** [comment]
@adubovik , please, pay attention on support attachment links also
