### ISSUE TITLE
Add support for Cohere Embedding Models in the Bedrock Adapter

### ISSUE THREAD

**Issue by YuryZhylko** [epam/ai-dial-core#406]
As a user, I want to be able to access Cohere Embedding models on Bedrock via the DIAL API leveraging OpenAI, LangChain or LlamaIndex Embeddings interface.

**Comment by adubovik** [comment]
It will be supported by PR https://github.com/epam/ai-dial-adapter-bedrock/pull/132

**Comment by adubovik** [comment]
The fix was merged into development: https://github.com/epam/ai-dial-adapter-bedrock/pull/132
