### ISSUE TITLE
Routing is too permissive

### ISSUE THREAD

**Issue by adubovik** [epam/ai-dial-core#41]
Regexps at `/src/main/java/com/epam/aidial/core/controller/ControllerSelector.java` are too permissive.

E.g. the regexp:

```java
private static final Pattern PATTERN_DEPLOYMENTS = Pattern.compile("/+openai/deployments");
```

allows the following paths:
1. `HOST/openai/deployments` (which is expected)
2.`HOST/foobar/openai/deployments` (not expected) 
3.`HOST/openai/deployments_foobar` (not expected)

**Comment by astsiapanay** [comment]
fixed by https://github.com/epam/ai-dial-core/pull/200
