### ISSUE TITLE
'URL bucket doesn't match' error appears if to create an unpublish request for some conversations

### ISSUE THREAD

**Issue by VolhaBazhkova** [epam/ai-dial-core#463]
1. Log on staging env via admin (Auth0) (use 1Passoword to find admin credentials)
2. In Organization section hover over the folder 'VB + DK folder in the change path' > click on three dots > click on Unpublish
3. Type any name for the request ( at the top left corner on the pop-up) and click on Send request button
-> error appears
![image](https://github.com/user-attachments/assets/fdff4710-3a1c-45da-a501-e75ec6cca1d2)

The same issue appears for the following conversations:
![image](https://github.com/user-attachments/assets/e95f449d-ed99-4b3d-a45f-ac3900c1f320)

Note: As the owner of VB + DK chat I can say that I used standard flow to publish the chat: 
1) created echo, attached file. The file is stored here: 
![image](https://github.com/user-attachments/assets/393438ed-37cf-4795-a497-56c60ddc6db9)
2) while publishing new folder in Change path was created: 
![image](https://github.com/user-attachments/assets/f8e9c8e8-250f-4595-9146-2a893d140140)
3) Approved by Admin. No any specific actions were done

**Comment by astsiapanay** [comment]
@VolhaBazhkova 

The request to unpublish the conversation contains resource to a private file. So there is something wrong with request data or how the file came to the conversation.

Core replaces links to files in the conversation provided from publish request.

**Comment by VolhaBazhkova** [comment]
Reported the ticket on chat side https://github.com/epam/ai-dial-chat/issues/2004

**Comment by astsiapanay** [comment]
It turned out the front-end has a defect in encoding resourceUrl in the publish request.
A special symbol `+` is not encoded properly.
See https://github.com/epam/ai-dial-chat/issues/2004
