### ISSUE TITLE
Error toast message on delete files from 'Manage attachments' from 'All files' section

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-core#493]
Preconditions:
there is at least one file in root of All files in Manage attachments 

Steps:
1. Open Manage attachments form
2. hover filename from 'All files' section
4. select Delete option in context menu, confirm deletion

Actual result:
error toast message is displayed "Discarding shared with you resource failed. Please try again later."
![image](https://github.com/user-attachments/assets/3f07d6c0-33bf-4830-87e3-c47f26bb8b47)

file is removed from all files

NOTE:
1. issue reproducible for files from folders inside 'All files'
2. NOT reproducible for files from 'Shared with me'

**Comment by VolhaBazhkova** [comment]
Moved the ticket to UI board https://github.com/epam/ai-dial-chat/issues/2193
