### ISSUE TITLE
Show DIAL Chat users information about money they spend on models

### ISSUE THREAD

**Issue by showroute** [epam/ai-dial-core#505]
**Problem statement:**

DIAL Chat end users are not aware of expenses on models connected to DIAL Core. That is not transparent for people that LLM usage is not for free. I suppose users can be provided with information about money they (or company) spend on models. It could bring some clarity and potentially prevent DIAL users (and companies) from high bills.

**Proposal:**

For example, expenses could be shown for users per conversation.

**Comment by astsiapanay** [comment]
Hello @showroute ,

The component https://github.com/epam/ai-dial-analytics-realtime is responsible for collecting statistics about models usage from DIAL Core. Eventually the stats are pushed to InfluxDB and available on Grafana dashboard.

The Core doesn't provide API for obtaining the info.
