### ISSUE TITLE
Implement user info enpoint

### ISSUE THREAD

**Issue by astsiapanay** [epam/ai-dial-core#522]
To access the endpoint, the user must be authenticated with API key or access token:

```
GET <dial-url>/v1/user/info
```

Successful API key response (HTTP 200 OK):
```
{
    "project": "EPM-RTC-RAIL-DEV",
    "roles": ["default"]
}
```

Successful access token response (HTTP 200 OK):
```
{   
    "roles": ["BA"],
    "userClaims": {
      "email": "user_email",
      "sub": "user_sum"
    }
}
```

The field userClaims contains claims to be extracted from access token.
Unsuccessful responses:

1. Invalid credentials provided (HTTP 400 Bad Request): neither API key nor access token provided
2. Unauthenticated user (HTTP 401 Unauthorized): bad credentials

**Comment by sr-remsha** [comment]
[API reference](https://epam-rail.com/dial_api#/paths/~1v1~1user~1info/get)
