### ISSUE TITLE
Change upstreams balancing algorithm

### ISSUE THREAD

**Issue by astsiapanay** [epam/ai-dial-core#576]
List of tasks:

- [x] Issue #585 
- [X] Issue #586  
- [x] Issue #587 
- [X] Issue #588 
- [x] Issue #589

**Comment by sr-remsha** [comment]
@astsiapanay  Please review the [documentation ](https://docs.epam-rail.com/tutorials/load-balancer)and notify if changes are required

**Comment by astsiapanay** [comment]
@sr-remsha  we need to update the documentation according to changes in the load balancing algorithm.

**Comment by sr-remsha** [comment]
[Updated document](https://docs.dialx.ai/platform/core/load-balancer)
